apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      foo: bar
  replicas: 3
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
